# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'targets/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'targets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  checkStyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #Step de carga de resultado previo
#    - name: Download a single artifact
#      uses: actions/download-artifact@v2
#      with:
#        name: checkstyle-result.xml

    #Step de obtenci√≥n de la cantidad de errores anteriores
#    - name: Get previous value
#      shell: bash
#      run: |
#        previous_errors=$(cat target/checkstyle-result.xml | grep error | wc -l)
#        echo Numbers of error = $previous_errors

    #Step de creacion de nuevo reporte
    - name: CheckStyle with Maven
      run: mvn -B verify checkstyle:checkstyle
    - uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkstyle-result.xml'

    #Step de subida de nuevo reporte
    - run: mkdir staging && cp target/checkstyle-result.xml staging
    - uses: actions/upload-artifact@v2
      with:
        name: checkstyle-result.xml
        path: staging
